### ISSUE TITLE
You can run animations in multi-threaded mode to improve processor performance

### ISSUE THREAD

**Issue by WOLFxxxxxx** [Kirandeep-Singh-Khehra/raylib-3d-anim-system#1]
https://guillaumeblanc.github.io/ozz-animation/samples/multithread/

**Comment by Kirandeep-Singh-Khehra** [comment]
Multi-threading is user's choice. It can have more chaos. And i don't think multithreading can do things fast as there is no waiting(like io blocking) or need to wait in any place. So, it will add complexity to system and context switching will be an overhead with no positive advantage. So, multithreading is not an option. And `Skeleton` and `Pose` have pointers to arrays. So managing thread safety will also be an issue and will make process slower.
